import logging
import httpx
import google.generativeai as genai
from typing import Optional
from app.services.api_key_manager import APIKeyManager

logger = logging.getLogger(__name__)

class LLMClient:
    def __init__(self, api_key_manager: APIKeyManager):
        self.api_key_manager = api_key_manager
        self.google_api_key_configured = False
        # Configure Gemini if key exists
        google_key = self.api_key_manager.get_next_key("google")
        if google_key:
            try:
                genai.configure(api_key=google_key)
                self.google_api_key_configured = True
                logger.info("Google Gemini API configured.")
            except Exception as e:
                logger.error(f"Failed to configure Google Gemini API: {e}")
        else:
            logger.warning("Google API key not found in APIKeyManager for LLMClient.")

    async def call_gemini(self, prompt: str, model_name: str = "gemini-1.5-flash-latest") -> str:
        if not self.google_api_key_configured:
            return "Error: Google Gemini API not configured."
        try:
            model = genai.GenerativeModel(model_name)
            response = await model.generate_content_async(prompt)
            if response.parts:
                return response.text
            elif response.prompt_feedback and response.prompt_feedback.block_reason:
                logger.warning(f"Gemini response blocked. Reason: {response.prompt_feedback.block_reason_message}")
                return f"Error: Content generation blocked by safety settings ({response.prompt_feedback.block_reason_message})."
            return "Error: No content generated by Gemini or unknown error."
        except Exception as e:
            logger.error(f"Error calling Gemini API ({model_name}): {e}", exc_info=True)
            return f"Error communicating with Gemini: {str(e)}"

    async def call_openrouter(self, model_name: str, prompt: str, system_prompt: Optional[str] = None) -> str:
        openrouter_key = self.api_key_manager.get_next_key("openrouter")
        if not openrouter_key:
            return "Error: OpenRouter API key not configured."

        headers = {
            "Authorization": f"Bearer {openrouter_key}",
            "Content-Type": "application/json"
        }
        messages = []
        if system_prompt:
            messages.append({"role": "system", "content": system_prompt})
        messages.append({"role": "user", "content": prompt})
        
        data = {
            "model": model_name,
            "messages": messages
        }
        api_url = "https://openrouter.ai/api/v1/chat/completions"

        try:
            async with httpx.AsyncClient(timeout=120.0) as client:
                response = await client.post(api_url, headers=headers, json=data)
                response.raise_for_status()
                result = response.json()
                if result.get("choices") and result["choices"][0].get("message"):
                    return result["choices"][0]["message"]["content"]
                logger.error(f"Unexpected OpenRouter response format: {result}")
                return "Error: Unexpected response format from OpenRouter."
        except httpx.HTTPStatusError as e:
            logger.error(f"HTTP error calling OpenRouter API ({model_name}): {e.response.status_code} - {e.response.text}", exc_info=True)
            return f"Error with OpenRouter API ({e.response.status_code}): {e.response.text}"
        except Exception as e:
            logger.error(f"Error calling OpenRouter API ({model_name}): {e}", exc_info=True)
            return f"Error communicating with OpenRouter: {str(e)}"