apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-dev-bot-platform-config
data:
  ENVIRONMENT: production
  LOG_LEVEL: INFO
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: ai_dev_bot
  REDIS_HOST: redis
  REDIS_PORT: "6379"