version: '3.8'

# This file is an overlay for the main docker-compose.yml.
# It adds proxy configuration to the 'app' service.
# To use it, run: docker-compose -f docker-compose.yml -f docker-compose.proxy.yml up

services:
  app:
    # Pass proxy settings to the Docker build process for 'pip install'
    build:
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
    # Pass proxy settings to the running container for runtime requests (e.g., to LLM APIs)
    environment:
      - HTTP_PROXY=${HTTP_PROXY}
      - HTTPS_PROXY=${HTTPS_PROXY}
      - NO_PROXY=${NO_PROXY}
    # Load the proxy settings from a dedicated .env.proxy file
    env_file:
      - .env.proxy